# Generated by Django 4.2.1 on 2023-05-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historyApp', '0002_topic_question_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
