# Generated by Django 4.2.1 on 2023-05-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyApp', '0004_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
